//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBankingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountRequest()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int Service_Reference_Number { get; set; }
        public string Title { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Last_Name { get; set; }
        public string Father_Name { get; set; }
        public string Gender { get; set; }
        public System.DateTime Date_Of_Birth { get; set; }
        public long Mobile_Number { get; set; }
        public string Email_Id { get; set; }
        public string Aadhar { get; set; }
        public string Residential_Address { get; set; }
        public string Permanent_Address { get; set; }
        public string Occupation_Type { get; set; }
        public string Source_Of_Income { get; set; }
        public Nullable<decimal> Gross_Annual_Income { get; set; }
        public Nullable<bool> Opt_Debit_Card { get; set; }
        public Nullable<bool> Opt_Net_Banking { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Requested_At { get; set; }
        public Nullable<System.DateTime> Approved_At { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
