//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBankingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Accounts = new HashSet<Account>();
            this.InternetBankings = new HashSet<InternetBanking>();
        }
    
        public int Customer_Id { get; set; }
        public Nullable<int> Service_Reference_Number { get; set; }
        public string Full_Name { get; set; }
        public Nullable<long> Mobile_Number { get; set; }
        public string Email_Id { get; set; }
        public string Aadhar { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
    
        public virtual AccountRequest AccountRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternetBanking> InternetBankings { get; set; }
    }
}
