//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBankingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebitCard
    {
        public long Debit_Card_Number { get; set; }
        public Nullable<long> Account_Number { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public Nullable<int> CVV { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
