//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBankingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternetBanking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InternetBanking()
        {
            this.OtpRequests = new HashSet<OtpRequest>();
            this.Payees = new HashSet<Payee>();
            this.SupportMessages = new HashSet<SupportMessage>();
        }
    
        public string User_Id { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<long> Account_Number { get; set; }
        public string Login_Password { get; set; }
        public string Transaction_Password { get; set; }
        public Nullable<int> Failed_Attempts { get; set; }
        public Nullable<bool> Is_Locked { get; set; }
        public Nullable<System.DateTime> Locked_Time { get; set; }
        public Nullable<System.DateTime> Last_Login { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtpRequest> OtpRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payee> Payees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupportMessage> SupportMessages { get; set; }
    }
}
