//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBankingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtpRequest
    {
        public int Otp_Id { get; set; }
        public string User_Id { get; set; }
        public string Otp { get; set; }
        public Nullable<System.DateTime> Created_Time { get; set; }
        public Nullable<System.DateTime> Expires_At { get; set; }
        public Nullable<bool> Is_Used { get; set; }
    
        public virtual InternetBanking InternetBanking { get; set; }
    }
}
