//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBankingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payee
    {
        public int Payee_Id { get; set; }
        public string User_Id { get; set; }
        public string Beneficiary_Name { get; set; }
        public long Beneficiary_Account_Number { get; set; }
        public string Nickname { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
    
        public virtual InternetBanking InternetBanking { get; set; }
    }
}
