//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBankingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportMessage
    {
        public int Message_Id { get; set; }
        public string User_Id { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Sent_At { get; set; }
        public string Admin_Reply { get; set; }
        public Nullable<System.DateTime> Replied_At { get; set; }
        public string Status { get; set; }
    
        public virtual InternetBanking InternetBanking { get; set; }
    }
}
