//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineBankingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long Transaction_Id { get; set; }
        public Nullable<long> From_Account { get; set; }
        public Nullable<long> To_Account { get; set; }
        public string Transaction_Mode { get; set; }
        public string Transaction_Type { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
    }
}
